<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CronExpressionDescriptor" />
        <PackageReference Include="Quartz.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mars.Scheduler.Abstractions\Mars.Scheduler.Abstractions.csproj" />
    </ItemGroup>

</Project>
