<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>mdimai666.Mars.HttpSmartAuthFlow</PackageId>
        <Product>Mars.HttpSmartAuthFlow</Product>
        <Description>
            Mars.HttpSmartAuthFlow - automatic authentication for Flurl.Http library.
        </Description>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="AngleSharp" />
        <PackageReference Include="Flurl.Http" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>
    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Mars.HttpSmartAuthFlow.Integration.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
</Project>
