<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\Mars.Contracts\Mars.Contracts.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.XActions.Contracts\Mars.XActions.Contracts.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.Identity.Contracts\Mars.Identity.Contracts.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.Cms.Contracts\Mars.Cms.Contracts.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.Options.Contracts\Mars.Options.Contracts.csproj" />
    </ItemGroup>

</Project>
