<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Quartz" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Mars.Core\Mars.Core.csproj" />
        <ProjectReference Include="..\..\Mars.Data\Mars.Data.csproj" />
        <ProjectReference Include="..\..\Mars.Server.Abstractions\Mars.Server.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Contracts\Mars.Contracts.csproj" />
    </ItemGroup>

</Project>
