<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Quartz" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Mars.Core\Mars.Core.csproj" />
        <ProjectReference Include="..\..\Server\Mars.Server.Abstractions\Mars.Server.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Contracts\Mars.Contracts.csproj" />
        <ProjectReference Include="..\Mars.Scheduler.Contracts\Mars.Scheduler.Contracts.csproj" />
    </ItemGroup>

</Project>
