<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.Agents.AI.Harness" />
    <PackageReference Include="Microsoft.Extensions.AI.Ollama" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="OpenAI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Mars.Datasource\Mars.Datasource.Host\Mars.Datasource.Host.csproj" />
    <ProjectReference Include="..\..\Mars.Host.Shared\Mars.Host.Shared.csproj" />
    <ProjectReference Include="..\Mars.AiChat.Host.Shared\Mars.AiChat.Host.Shared.csproj" />
  </ItemGroup>

</Project>
