<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>mdimai666.Mars.Nodes.Core.Implements</PackageId>
        <Product>Mars.Nodes.Core.Implements</Product>
        <Description>
            Mars Nodes core Implements;
        </Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AngleSharp" />
        <PackageReference Include="DynamicExpresso.Core" />
        <PackageReference Include="Flurl.Http" />
        <PackageReference Include="Handlebars.Net" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="MQTTnet" />
        <PackageReference Include="MQTTnet.Extensions.TopicTemplate" />
        <PackageReference Include="Newtonsoft.Json" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Server\Mars.Server.Abstractions\Mars.Server.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.XActions.Abstractions\Mars.XActions.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.Notifications.Abstractions\Mars.Notifications.Abstractions.csproj" />
        <ProjectReference Include="..\..\Modules\Mars.HttpSmartAuthFlow\Mars.HttpSmartAuthFlow.csproj" />
        <ProjectReference Include="..\Mars.Nodes.Core\Mars.Nodes.Core.csproj" />
        <ProjectReference Include="..\Mars.Nodes.Abstractions\Mars.Nodes.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.Cms.Abstractions\Mars.Cms.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.Identity.Abstractions\Mars.Identity.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.Media.Abstractions\Mars.Media.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.SiteEngine.Abstractions\Mars.SiteEngine.Abstractions.csproj" />
    <ProjectReference Include="..\..\Mars.Modules\Mars.Options.Abstractions\Mars.Options.Abstractions.csproj" />
    <ProjectReference Include="..\..\Mars.Modules\Mars.TemplateEngine.Abstractions\Mars.TemplateEngine.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Mars.Nodes.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
