<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <PackageId>mdimai666.MarsEditors</PackageId>
        <Product>MarsEditors</Product>
        <Description>
            Shared project. Monaco Code editor depend from Mars backend
        </Description>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    </ItemGroup>

</Project>
