<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mars.Identity.Abstractions\Mars.Identity.Abstractions.csproj" />
        <ProjectReference Include="..\Mars.SSO.Contracts\Mars.SSO.Contracts.csproj" />
    </ItemGroup>

</Project>
