<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
        <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\src\AppFront.Shared\AppFront.Shared.csproj" />
        <ProjectReference Include="..\..\..\..\src\Mars.PxBlocks\Mars.PxBlocks.Workspace\Mars.PxBlocks.Workspace.csproj" />
    </ItemGroup>

</Project>
