//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.Nodes.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NodeRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NodeRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mars.Nodes.Core.Resources.NodeRes", typeof(NodeRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string StringOperationGroupName_add {
            get {
                return ResourceManager.GetString("StringOperationGroupName_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string StringOperationGroupName_all {
            get {
                return ResourceManager.GetString("StringOperationGroupName_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array.
        /// </summary>
        public static string StringOperationGroupName_array {
            get {
                return ResourceManager.GetString("StringOperationGroupName_array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basic.
        /// </summary>
        public static string StringOperationGroupName_basic {
            get {
                return ResourceManager.GetString("StringOperationGroupName_basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check.
        /// </summary>
        public static string StringOperationGroupName_check {
            get {
                return ResourceManager.GetString("StringOperationGroupName_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encode.
        /// </summary>
        public static string StringOperationGroupName_encode {
            get {
                return ResourceManager.GetString("StringOperationGroupName_encode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extract.
        /// </summary>
        public static string StringOperationGroupName_extract {
            get {
                return ResourceManager.GetString("StringOperationGroupName_extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string StringOperationGroupName_remove {
            get {
                return ResourceManager.GetString("StringOperationGroupName_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace.
        /// </summary>
        public static string StringOperationGroupName_replace {
            get {
                return ResourceManager.GetString("StringOperationGroupName_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stats.
        /// </summary>
        public static string StringOperationGroupName_stats {
            get {
                return ResourceManager.GetString("StringOperationGroupName_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transform.
        /// </summary>
        public static string StringOperationGroupName_transform {
            get {
                return ResourceManager.GetString("StringOperationGroupName_transform", resourceCulture);
            }
        }
    }
}
