<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>mdimai666.Mars.PxBlocks.Runtime</PackageId>
        <Description>
            PxBlock — это Programming x Block: среда, где код собирается как конструктор.
            Runtime: AST и tree-walking интерпретатор исполнения блоков в .NET (без кодогенерации).
        </Description>
    </PropertyGroup>

</Project>
