<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" />
    <PackageReference Include="MimeKit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Mars.Host.Shared\Mars.Host.Shared.csproj" />
    <ProjectReference Include="..\Mars.Identity.Abstractions\Mars.Identity.Abstractions.csproj" />
    <ProjectReference Include="..\Mars.Notifications.Abstractions\Mars.Notifications.Abstractions.csproj" />
  </ItemGroup>

</Project>
