<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Docker.DotNet" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Server\Mars.Server.Abstractions\Mars.Server.Abstractions.csproj" />
        <ProjectReference Include="..\Mars.Docker.Abstractions\Mars.Docker.Abstractions.csproj" />
        <ProjectReference Include="..\..\Server\Mars.Data\Mars.Data.csproj" />
    </ItemGroup>

</Project>
