<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Mars.TemplateEngine.Providers.ScribanProvider</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Scriban" />
    </ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\Mars.TemplateEngine.Abstractions\Mars.TemplateEngine.Abstractions.csproj" />
	</ItemGroup>

</Project>
