<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" />
    <PackageReference Include="Handlebars.Net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Server\Mars.Data\Mars.Data.csproj" />
    <ProjectReference Include="..\..\Server\Mars.Data.Repositories\Mars.Data.Repositories.csproj" />
    <ProjectReference Include="..\Mars.Options.Abstractions\Mars.Options.Abstractions.csproj" />
    <ProjectReference Include="..\..\Server\Mars.Server.Abstractions\Mars.Server.Abstractions.csproj" />
    <ProjectReference Include="..\Mars.XActions.Abstractions\Mars.XActions.Abstractions.csproj" />
    <ProjectReference Include="..\Mars.XActions.Contracts\Mars.XActions.Contracts.csproj" />
    <ProjectReference Include="..\Mars.SiteEngine.Abstractions\Mars.SiteEngine.Abstractions.csproj" />
    <ProjectReference Include="..\Mars.Cms.Abstractions\Mars.Cms.Abstractions.csproj" />
    <ProjectReference Include="..\Mars.Cms.Contracts\Mars.Cms.Contracts.csproj" />
    <ProjectReference Include="..\Mars.Identity.Abstractions\Mars.Identity.Abstractions.csproj" />
    <ProjectReference Include="..\Mars.Media.Abstractions\Mars.Media.Abstractions.csproj" />
    <ProjectReference Include="..\Mars.Media.Contracts\Mars.Media.Contracts.csproj" />
    <ProjectReference Include="..\Mars.Excel.Abstractions\Mars.Excel.Abstractions.csproj" />
    <ProjectReference Include="..\..\Modules\EditorJsBlazored\EditorJsBlazored\EditorJsBlazored.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Mars.Server.Tests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Mars.Integration.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
