<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>mdimai666.Mars.Notifications.Contracts</PackageId>
        <Description>Mars notifications wire contracts: notifications DTOs.</Description>
    </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Mars.Core\Mars.Core.csproj" />
    <ProjectReference Include="..\..\Mars.Contracts\Mars.Contracts.csproj" />
  </ItemGroup>

</Project>
