<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mars.CommandLine.Abstractions\Mars.CommandLine.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Mars.CommandLine.Scripting.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
