<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\Mars.Data.InMemory\Mars.Data.InMemory.csproj" />
        <ProjectReference Include="..\Mars.Data.PostgreSQL\Mars.Data.PostgreSQL.csproj" />
        <ProjectReference Include="..\Mars.Data\Mars.Data.csproj" />
        <ProjectReference Include="..\Mars.Data.Repositories\Mars.Data.Repositories.csproj" />
        <ProjectReference Include="..\Mars.Server.Abstractions\Mars.Server.Abstractions.csproj" />
    </ItemGroup>
</Project>
