<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>mdimai666.Mars.Cms.Abstractions</PackageId>
        <Description>Mars CMS server abstractions: services and extension points.</Description>
    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Mars.Core\Mars.Core.csproj" />
    <ProjectReference Include="..\..\Mars.Contracts\Mars.Contracts.csproj" />
    <ProjectReference Include="..\Mars.Cms.Contracts\Mars.Cms.Contracts.csproj" />
    <ProjectReference Include="..\Mars.Media.Abstractions\Mars.Media.Abstractions.csproj" />
  </ItemGroup>


  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Mars.Server.Tests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Mars.Integration.Tests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Mars.E2E.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>