<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Server\Mars.Server\Mars.Server.csproj" />
        <ProjectReference Include="..\..\tests\Mars.Integration.Tests\Mars.Integration.Tests.csproj" />
    </ItemGroup>

</Project>
