<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <Compile Remove="EmitVariantExample.cs" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Mars.Data\Mars.Data.csproj" />
      <ProjectReference Include="..\..\Mars.Server.Abstractions\Mars.Server.Abstractions.csproj" />
    </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Mars.Cms.Abstractions\Mars.Cms.Abstractions.csproj" />
  </ItemGroup>

</Project>
