<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>mdimai666.Mars.Media.Contracts</PackageId>
        <Description>Mars media wire contracts: media files and folders DTOs.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Mars.Contracts\Mars.Contracts.csproj" />
    </ItemGroup>

</Project>
