<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
	  <PackageReference Include="Microting.EntityFrameworkCore.MySql" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Mars.Datasource\Mars.Datasource.csproj" />
		<ProjectReference Include="..\Mars.Datasource.Abstractions\Mars.Datasource.Abstractions.csproj" />
	</ItemGroup>
</Project>
