<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <EnableDynamicLoading>true</EnableDynamicLoading>

        <PackageId>mdimai666.Mars.Plugin.Kit.Front</PackageId>
        <Product>Mars.Plugin.Kit.Front</Product>
        <Description>
            Packages kits for plugin frontend development
        </Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Admin\Mars.Admin.Framework\Mars.Admin.Framework.csproj" />
        <ProjectReference Include="..\..\Mars.Nodes\Mars.Nodes.FormEditor\Mars.Nodes.FormEditor.csproj" />
        <ProjectReference Include="..\..\Mars.Nodes\Mars.Nodes.Front.Abstractions\Mars.Nodes.Front.Abstractions.csproj" />
        <ProjectReference Include="..\Mars.Plugin.Front\Mars.Plugin.Front.csproj" />
    </ItemGroup>

</Project>
