<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\src\Mars.Admin\Mars.Admin.csproj" />
    </ItemGroup>

</Project>
