<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>mdimai666.Mars.XActions.Abstractions</PackageId>
        <Description>Mars XActions server abstractions: services and extension points.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mars.XActions.Contracts\Mars.XActions.Contracts.csproj" />
    </ItemGroup>

</Project>
