<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\..\Mars.Server.Abstractions\Mars.Server.Abstractions.csproj" />
        <ProjectReference Include="..\Mars.SemanticKernel.Abstractions\Mars.SemanticKernel.Abstractions.csproj" />
        <ProjectReference Include="..\Mars.Cms.Abstractions\Mars.Cms.Abstractions.csproj" />
        <ProjectReference Include="..\Mars.SiteEngine.Abstractions\Mars.SiteEngine.Abstractions.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Content Include="Skills\**\*.md">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Mars.AiServices.Integration.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
