<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <PackageId>mdimai666.BlazoredHtmlRender</PackageId>
        <!-- Собственная версия пакета, не привязана к MarsAppVersion -->
        <Version>0.5.0-alpha.1</Version>
        <Product>BlazoredHtmlRender</Product>
        <Description>
            A Blazor component for rendering a plain HTML string in Blazor page;
        </Description>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>BL0007</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
        <PackageReference Include="HtmlAgilityPack" />
        <PackageReference Include="OneOf" />
    </ItemGroup>

</Project>
