<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\Mars.Server.Abstractions\Mars.Server.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Server.Contracts\Mars.Server.Contracts.csproj" />
        <ProjectReference Include="..\..\Mars.Options\Mars.Options\Mars.Options.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.SiteEngine.Abstractions\Mars.SiteEngine.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Test.Mars.Server</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Mars.Integration.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
