<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
      <NoWarn>BL0007;CSS102;CSS104;</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Mars.Nodes\Mars.Nodes.FormEditor\Mars.Nodes.FormEditor.csproj" />
    <ProjectReference Include="..\..\Admin\Mars.Admin.Framework\Mars.Admin.Framework.csproj" />
    <ProjectReference Include="..\Mars.Options.Abstractions\Mars.Options.Abstractions.csproj" />
    <ProjectReference Include="..\Mars.SemanticKernel.Contracts\Mars.SemanticKernel.Contracts.csproj" />
  </ItemGroup>

</Project>
