<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>mdimai666.Mars.PxBlocks.Core</PackageId>
        <Description>
            PxBlock — это Programming x Block: среда, где код собирается как конструктор.
            Core: модели без JS — определения блоков (fluent PxMaster), реестр типов, тулбокс.
        </Description>
    </PropertyGroup>

</Project>
