<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" />
        <PackageReference Include="Handlebars.Net" />
        <PackageReference Include="Handlebars.Net.Extension.Json" />
        <PackageReference Include="Handlebars.Net.Extension.NewtonsoftJson" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Server\Mars.Server.Abstractions\Mars.Server.Abstractions.csproj" />
        <ProjectReference Include="..\..\src\Mars.Contracts\Mars.Contracts.csproj" />
        <ProjectReference Include="..\..\tests\Mars.Test.Common\Mars.Test.Common.csproj" />
    </ItemGroup>

</Project>
