<Project Sdk="Microsoft.NET.Sdk.Razor">

    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    </ItemGroup>

    <PropertyGroup>
        <NoWarn>BL0007</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="wwwroot\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Mars.Admin.Framework\Mars.Admin.Framework.csproj" />
        <ProjectReference Include="..\..\Modules\MarsCodeEditor2\MarsCodeEditor2.csproj" />
        <ProjectReference Include="..\Mars.Options.Abstractions\Mars.Options.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.Media.Contracts\Mars.Media.Contracts.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.SiteEngine.Contracts\Mars.SiteEngine.Contracts.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.SSO.Contracts\Mars.SSO.Contracts.csproj" />
        <ProjectReference Include="..\..\Mars.Server.Contracts\Mars.Server.Contracts.csproj" />
        <ProjectReference Include="..\..\Plugin\Mars.Plugin.Contracts\Mars.Plugin.Contracts.csproj" />
    </ItemGroup>

</Project>
