//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mars.Shared.Resources.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the action.
        /// </summary>
        public static string ActionConfirmationPrompt {
            get {
                return ResourceManager.GetString("ActionConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnketaAnswer.
        /// </summary>
        public static string AnketaAnswer {
            get {
                return ResourceManager.GetString("AnketaAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnketaAnswers.
        /// </summary>
        public static string AnketaAnswer_many {
            get {
                return ResourceManager.GetString("AnketaAnswer.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnketaQuestion.
        /// </summary>
        public static string AnketaQuestion {
            get {
                return ResourceManager.GetString("AnketaQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnketaQuestions.
        /// </summary>
        public static string AnketaQuestion_many {
            get {
                return ResourceManager.GetString("AnketaQuestion.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Button_SignIn {
            get {
                return ResourceManager.GetString("Button_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By date.
        /// </summary>
        public static string ByDate {
            get {
                return ResourceManager.GetString("ByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comment_many {
            get {
                return ResourceManager.GetString("Comment.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed successfully.
        /// </summary>
        public static string CompletedSuccessfully {
            get {
                return ResourceManager.GetString("CompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactPerson.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactPersons.
        /// </summary>
        public static string ContactPerson_many {
            get {
                return ResourceManager.GetString("ContactPerson.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest.
        /// </summary>
        public static string Contest {
            get {
                return ResourceManager.GetString("Contest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contests.
        /// </summary>
        public static string Contest_many {
            get {
                return ResourceManager.GetString("Contest.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Css class.
        /// </summary>
        public static string CssClass {
            get {
                return ResourceManager.GetString("CssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Css style.
        /// </summary>
        public static string CssStyle {
            get {
                return ResourceManager.GetString("CssStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to show.
        /// </summary>
        public static string DataGrid__EmptyContent {
            get {
                return ResourceManager.GetString("DataGrid__EmptyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date deleted.
        /// </summary>
        public static string DateDeleted {
            get {
                return ResourceManager.GetString("DateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified.
        /// </summary>
        public static string DateModified {
            get {
                return ResourceManager.GetString("DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string DeletionConfirmationMessage {
            get {
                return ResourceManager.GetString("DeletionConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Document_many {
            get {
                return ResourceManager.GetString("Document.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Excel.
        /// </summary>
        public static string DownloadExcel {
            get {
                return ResourceManager.GetString("DownloadExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid e-mail address..
        /// </summary>
        public static string EmailInvalidMessage {
            get {
                return ResourceManager.GetString("EmailInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled features.
        /// </summary>
        public static string EnabledFeatures {
            get {
                return ResourceManager.GetString("EnabledFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excerpt.
        /// </summary>
        public static string Excerpt {
            get {
                return ResourceManager.GetString("Excerpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedbacks.
        /// </summary>
        public static string Feedbacks {
            get {
                return ResourceManager.GetString("Feedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoLocation.
        /// </summary>
        public static string GeoLocation {
            get {
                return ResourceManager.GetString("GeoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoLocations.
        /// </summary>
        public static string GeoLocation_many {
            get {
                return ResourceManager.GetString("GeoLocation.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoLocationType.
        /// </summary>
        public static string GeoLocationType {
            get {
                return ResourceManager.GetString("GeoLocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoLocationTypes.
        /// </summary>
        public static string GeoLocationType_many {
            get {
                return ResourceManager.GetString("GeoLocationType.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoMunicipality.
        /// </summary>
        public static string GeoMunicipality {
            get {
                return ResourceManager.GetString("GeoMunicipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoMunicipalitys.
        /// </summary>
        public static string GeoMunicipality_many {
            get {
                return ResourceManager.GetString("GeoMunicipality.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoMunicType.
        /// </summary>
        public static string GeoMunicType {
            get {
                return ResourceManager.GetString("GeoMunicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoMunicTypes.
        /// </summary>
        public static string GeoMunicType_many {
            get {
                return ResourceManager.GetString("GeoMunicType.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoRegion.
        /// </summary>
        public static string GeoRegion {
            get {
                return ResourceManager.GetString("GeoRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoRegions.
        /// </summary>
        public static string GeoRegion_many {
            get {
                return ResourceManager.GetString("GeoRegion.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoRegionCenter.
        /// </summary>
        public static string GeoRegionCenter {
            get {
                return ResourceManager.GetString("GeoRegionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoRegionCenters.
        /// </summary>
        public static string GeoRegionCenter_many {
            get {
                return ResourceManager.GetString("GeoRegionCenter.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        public static string InvalidPhoneNumberError {
            get {
                return ResourceManager.GetString("InvalidPhoneNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert roles.
        /// </summary>
        public static string InvertRoles {
            get {
                return ResourceManager.GetString("InvertRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or Email.
        /// </summary>
        public static string LoginOrEmail {
            get {
                return ResourceManager.GetString("LoginOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access your account.
        /// </summary>
        public static string LoginPage_AccessYourAccount {
            get {
                return ResourceManager.GetString("LoginPage_AccessYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet.
        /// </summary>
        public static string Meet {
            get {
                return ResourceManager.GetString("Meet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meets.
        /// </summary>
        public static string Meet_many {
            get {
                return ResourceManager.GetString("Meet.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta field.
        /// </summary>
        public static string MetaField {
            get {
                return ResourceManager.GetString("MetaField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta fields.
        /// </summary>
        public static string MetaFields {
            get {
                return ResourceManager.GetString("MetaFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiddleName.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator.
        /// </summary>
        public static string Moderator {
            get {
                return ResourceManager.GetString("Moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified at.
        /// </summary>
        public static string ModifiedAt {
            get {
                return ResourceManager.GetString("ModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav menu.
        /// </summary>
        public static string NavMenu {
            get {
                return ResourceManager.GetString("NavMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav menus.
        /// </summary>
        public static string NavMenus {
            get {
                return ResourceManager.GetString("NavMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records.
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenIDClientOption.Authority..
        /// </summary>
        public static string OpenIDClientOption_Authority {
            get {
                return ResourceManager.GetString("OpenIDClientOption.Authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the &apos;client_id&apos;.
        /// </summary>
        public static string OpenIDClientOption_ClientId {
            get {
                return ResourceManager.GetString("OpenIDClientOption.ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name of the identity provider.
        /// </summary>
        public static string OpenIDClientOption_Title {
            get {
                return ResourceManager.GetString("OpenIDClientOption.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin.
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Post_many {
            get {
                return ResourceManager.GetString("Post.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post categories.
        /// </summary>
        public static string PostCategories {
            get {
                return ResourceManager.GetString("PostCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post category.
        /// </summary>
        public static string PostCategory {
            get {
                return ResourceManager.GetString("PostCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post category type.
        /// </summary>
        public static string PostCategoryType {
            get {
                return ResourceManager.GetString("PostCategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post category types.
        /// </summary>
        public static string PostCategoryTypes {
            get {
                return ResourceManager.GetString("PostCategoryTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostType.
        /// </summary>
        public static string PostType {
            get {
                return ResourceManager.GetString("PostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostTypes.
        /// </summary>
        public static string PostType_many {
            get {
                return ResourceManager.GetString("PostType.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post types.
        /// </summary>
        public static string PostTypes {
            get {
                return ResourceManager.GetString("PostTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportCounter.
        /// </summary>
        public static string ReportCounter {
            get {
                return ResourceManager.GetString("ReportCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportCounters.
        /// </summary>
        public static string ReportCounter_many {
            get {
                return ResourceManager.GetString("ReportCounter.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportCounterTemplate.
        /// </summary>
        public static string ReportCounterTemplate {
            get {
                return ResourceManager.GetString("ReportCounterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportCounterTemplates.
        /// </summary>
        public static string ReportCounterTemplate_many {
            get {
                return ResourceManager.GetString("ReportCounterTemplate.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug.
        /// </summary>
        public static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting order.
        /// </summary>
        public static string SortingOrder {
            get {
                return ResourceManager.GetString("SortingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusChangeHistory.
        /// </summary>
        public static string StatusChangeHistory {
            get {
                return ResourceManager.GetString("StatusChangeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusChangeHistorys.
        /// </summary>
        public static string StatusChangeHistory_many {
            get {
                return ResourceManager.GetString("StatusChangeHistory.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statuses.
        /// </summary>
        public static string Statuses {
            get {
                return ResourceManager.GetString("Statuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For field {0} maximum {1}, minimum length {2}.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For field {0} the maximum length is {1}.
        /// </summary>
        public static string StringLengthMax {
            get {
                return ResourceManager.GetString("StringLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryInformation.
        /// </summary>
        public static string SummaryInformation {
            get {
                return ResourceManager.GetString("SummaryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryInformations.
        /// </summary>
        public static string SummaryInformation_many {
            get {
                return ResourceManager.GetString("SummaryInformation.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user did not provide an email.
        /// </summary>
        public static string The_user_did_not_provide_an_email {
            get {
                return ResourceManager.GetString("The user did not provide an email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not have email.
        /// </summary>
        public static string The_user_does_not_have_email {
            get {
                return ResourceManager.GetString("The user does not have email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0} results found.
        /// </summary>
        public static string TotalResultsFound {
            get {
                return ResourceManager.GetString("TotalResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name.
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string User_many {
            get {
                return ResourceManager.GetString("User.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserType.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserTypes.
        /// </summary>
        public static string UserTypes {
            get {
                return ResourceManager.GetString("UserTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is not a valid email address..
        /// </summary>
        public static string v_email {
            get {
                return ResourceManager.GetString("v_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For field {0} maximum {1}, minimum length {2}.
        /// </summary>
        public static string v_range {
            get {
                return ResourceManager.GetString("v_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is required..
        /// </summary>
        public static string v_required {
            get {
                return ResourceManager.GetString("v_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors occurred..
        /// </summary>
        public static string ValidationErrorsOccurredTitle {
            get {
                return ResourceManager.GetString("ValidationErrorsOccurredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer.
        /// </summary>
        public static string Viewer {
            get {
                return ResourceManager.GetString("Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zayavka.
        /// </summary>
        public static string Zayavka {
            get {
                return ResourceManager.GetString("Zayavka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zayavkas.
        /// </summary>
        public static string Zayavka_many {
            get {
                return ResourceManager.GetString("Zayavka.many", resourceCulture);
            }
        }
    }
}
