<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>mdimai666.Mars.Docker.Abstractions</PackageId>
        <Description>Mars Docker integration server abstractions: services and extension points.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Mars.Contracts\Mars.Contracts.csproj" />
        <ProjectReference Include="..\Mars.Docker.Contracts\Mars.Docker.Contracts.csproj" />
    </ItemGroup>
</Project>
