<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Testing.Platform" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Mars.Modules\Mars.Forms.Abstractions\Mars.Forms.Abstractions.csproj" />
        <ProjectReference Include="..\..\src\Mars.Modules\Mars.Forms.Front\Mars.Forms.Front.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

</Project>
