<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\..\Mars.Core\Mars.Core.csproj" />
        <ProjectReference Include="..\Mars.Data.InMemory\Mars.Data.InMemory.csproj" />
        <ProjectReference Include="..\Mars.Data.PostgreSQL\Mars.Data.PostgreSQL.csproj" />
        <ProjectReference Include="..\Mars.Data\Mars.Data.csproj" />
        <ProjectReference Include="..\Mars.Server.Abstractions\Mars.Server.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.Options.Abstractions\Mars.Options.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.Identity.Abstractions\Mars.Identity.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.Cms.Abstractions\Mars.Cms.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.Media.Abstractions\Mars.Media.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Mars.Server.Tests</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Mars.Integration.Tests</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Mars.E2E.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
</Project>
