<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>mdimai666.Mars.Contracts</PackageId>
        <Product>Mars.Contracts</Product>
        <Description>
            Mars global wire contracts: shared DTOs, interfaces and WASM-safe helpers.
        </Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mars.Core\Mars.Core.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Resources\AppRes.Designer.cs">
            <DependentUpon>AppRes.resx</DependentUpon>
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
        </Compile>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Update="Resources\AppRes.resx">
            <SubType>Designer</SubType>
            <LastGenOutput>AppRes.Designer.cs</LastGenOutput>
            <Generator>PublicResXFileCodeGenerator</Generator>
        </EmbeddedResource>
    </ItemGroup>
</Project>
