<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Testing.Platform" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Mars.Modules\Mars.SemanticKernel.CMS\Mars.SemanticKernel.CMS.csproj" />
        <ProjectReference Include="..\..\src\Mars.Modules\Mars.SemanticKernel.Abstractions\Mars.SemanticKernel.Abstractions.csproj" />
        <ProjectReference Include="..\..\src\Mars.Modules\Mars.SemanticKernel.Host\Mars.SemanticKernel.Host.csproj" />
        <ProjectReference Include="..\Mars.Test.Common\Mars.Test.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

</Project>
