<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>mdimai666.Mars.SiteEngine.Abstractions</PackageId>
        <Description>Mars site engine server abstractions: services and extension points.</Description>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="DynamicExpresso.Core" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Mars.Core\Mars.Core.csproj" />
        <ProjectReference Include="..\..\Mars.Contracts\Mars.Contracts.csproj" />
        <ProjectReference Include="..\Mars.SiteEngine.Contracts\Mars.SiteEngine.Contracts.csproj" />
        <ProjectReference Include="..\..\Mars.Nodes\Mars.Nodes.Core\Mars.Nodes.Core.csproj" />
        <ProjectReference Include="..\Mars.Cms.Abstractions\Mars.Cms.Abstractions.csproj" />
        <ProjectReference Include="..\Mars.Media.Abstractions\Mars.Media.Abstractions.csproj" />
        <ProjectReference Include="..\Mars.Identity.Abstractions\Mars.Identity.Abstractions.csproj" />
        <ProjectReference Include="..\..\Server\Mars.Server.Abstractions\Mars.Server.Abstractions.csproj" />
        <ProjectReference Include="..\..\Server\Mars.Server.Contracts\Mars.Server.Contracts.csproj" />
        <ProjectReference Include="..\Mars.TemplateEngine.Abstractions\Mars.TemplateEngine.Abstractions.csproj" />
    </ItemGroup>

</Project>
