<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Private>false</Private>
        <Product>Mars.Server</Product>
    </PropertyGroup>

    <PropertyGroup>
        <!-- Swagger IncludeXmlComments читает xml-документацию исполняемой сборки -->
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.FeatureManagement.AspNetCore" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
        <PackageReference Include="Npgsql" />
        <PackageReference Include="Humanizer" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mars.Data\Mars.Data.csproj" />
        <ProjectReference Include="..\Mars.Data.Repositories\Mars.Data.Repositories.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.Options.Abstractions\Mars.Options.Abstractions.csproj" />
        <ProjectReference Include="..\Mars.Server.Abstractions\Mars.Server.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Contracts\Mars.Contracts.csproj" />
        <ProjectReference Include="..\Mars.Server.Contracts\Mars.Server.Contracts.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.XActions.Abstractions\Mars.XActions.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.CommandLine.Abstractions\Mars.CommandLine.Abstractions.csproj" />
        <ProjectReference Include="..\..\Mars.Modules\Mars.Scheduler.Abstractions\Mars.Scheduler.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
            <_Parameter1>SourceRevisionId</_Parameter1>
            <_Parameter2>$(SourceRevisionId)</_Parameter2>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
            <_Parameter1>RepositoryUrl</_Parameter1>
            <_Parameter2>$(RepositoryUrl)</_Parameter2>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Mars.Server.Tests</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Mars.Integration.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
